name: Xmas-2023

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        echo this is my run env
        echo "${{env.RUN_MODE}}" > "run.txt"
        cat run.txt
        echo this is the end
        echo I do something here
        echo RUN_MODE=${{env.RUN_MODE}} >> .env
        cat .env
        echo end something
        npm install

        # generate `dist` folder with RUN_MODE=production
        npm run build

        mkdir build
        cp -r dist build
        cp -r assets build
      env:
        RUN_MODE: ${{ vars.RUN_MODE }}
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
