name: Xmas-2023-test

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        echo RUN_MODE=$RUN_MODE >> .env
        cat .env

        yarn
        yarn run build
      env:
        RUN_MODE: ${{ env.RUN_MODE }}